### ISSUE TITLE
Nuget package 1.0.3 build for wrong platform target

### ISSUE THREAD

**Issue by andreyleskov** [Pro-Coded/Pro.NBench.xUnit#5]
Please rebuild package got .net core, as current one (1.0.3) is dependent on .net 4.5.2 librasies.
It makes nbench tests not launchable. Now I have to use own-build version from https://ci.appveyor.com/project/ContextCore/pro-nbench-xunit
I can grant you access to this build pipeline, only email is need.

**Comment by mcquiggd** [comment]
Darn it, I don't seem to get notifications for issues.

I'll update and republish. Apologies for the delay...

**Comment by mcquiggd** [comment]
Version 1.0.4 pushed to NuGet. Feedback welcome!
