### ISSUE TITLE
Exception(s) within fact method do not fail the test

### ISSUE THREAD

**Issue by Farishta** [Pro-Coded/Pro.NBench.xUnit#6]
G'day

I would like to report the issue with the [NBenchFact] test method. In case of any uncaught/unexpected exception occurs within the code, it does not fail and marks it passed. See below example:

>  [NBenchFact]
        [PerfBenchmark(RunMode = RunMode.Iterations, TestMode = TestMode.Test, NumberOfIterations = 1, SkipWarmups = true)]
        [ElapsedTimeAssertion(MaxTimeMilliseconds = 100)]
        public void TestExceptionFailure()
        {
            throw new Exception("this exception should fail the test. BUT it does not.");
        }

The test should be failed if the normal flow is not completed.

**Comment by mcquiggd** [comment]
@Farishta Thanks for reporting this, I will investigate and inform of a fix.

**Comment by Farishta** [comment]
@mcquiggd 

Please have a look at the PR https://github.com/Pro-Coded/Pro.NBench.xUnit/pull/7, where the possible fix was provided.

Cheers.

**Comment by wsaeed** [comment]
Can you please release the above commit?

**Comment by mcquiggd** [comment]
Hello @Farishta , @wsaeed - version 1.05 has been released and published to Nuget; if you still have problems, let me know and I will re-open this...
